# Generated by Django 5.0.10 on 2025-02-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cicloahorro',
            old_name='monto_total',
            new_name='monto_por_participante',
        ),
        migrations.AddField(
            model_name='cicloahorro',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='cicloahorro',
            name='periodo',
            field=models.CharField(choices=[('SEMANAL', 'SEMANAL'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='participanteciclo',
            name='orden_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
